export const ENDPOINTS = {
  OVERVIEW: '/overview',
  APPROACH: '/approach',
  SIGNALS: '/signals',
  AGENTS: '/agents',
  TRENDS: '/trends',
  DATASET_PREVIEW: '/dataset/preview',
  HARDWARE: '/hardware',
  LOGS: '/logs',
  DECISION: '/decision',
  PREDICTIONS: '/predictions',
  EMERGENCY_CORRIDOR: '/signals/emergency-corridor',
  ADAPTIVE_MODE: '/signals/adaptive-mode',
  SIGNAL_MODE: '/signals/mode',
};
